"use client";

import { useState, useRef, useCallback, useEffect, useMemo } from "react";
import GoogleAd from "./GoogleAd";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
type Phase = "idle" | "loading" | "processing" | "ready" | "error";
type GradientKind = "linear" | "radial";
type RadialShape = "circle" | "ellipse";

interface Stop {
  color: string;
  position: number; // 0-100
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------
const MAX_FILE_BYTES = 20 * 1024 * 1024; // 20 MiB
const MAX_CANVAS_PX = 800;
const CLUSTER_COUNT = 6;
const CACHE_MAX = 10;
const STORAGE_KEY = "img2gradient_v2";

const VALID_MIMES = new Set([
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/gif",
  "image/bmp",
]);

// ---------------------------------------------------------------------------
// Pure helpers (no React dependency)
// ---------------------------------------------------------------------------
function clamp(v: number, lo: number, hi: number) {
  return Math.max(lo, Math.min(hi, Math.round(v)));
}

function rgbToHex(r: number, g: number, b: number) {
  const h = (n: number) =>
    clamp(n, 0, 255).toString(16).padStart(2, "0");
  return `#${h(r)}${h(g)}${h(b)}`;
}

function stopsToCSS(
  stops: Stop[],
  kind: GradientKind,
  angle: number,
  radialShape: RadialShape,
): string {
  const list = stops
    .filter((s) => s.color)
    .map((s) => `${s.color} ${s.position}%`)
    .join(", ");

  if (kind === "linear") {
    return `linear-gradient(${angle}deg, ${list})`;
  }
  return `radial-gradient(${radialShape} at center, ${list})`;
}

function fullCSSText(
  stops: Stop[],
  kind: GradientKind,
  angle: number,
  radialShape: RadialShape,
) {
  const bg = stopsToCSS(stops, kind, angle, radialShape);
  return `/* Generated by img2gradient */\n.gradient-box {\n  width: 100%;\n  min-height: 300px;\n  background: ${bg};\n}\n`;
}

// ---------------------------------------------------------------------------
// Async K-Means++ on the main thread — chunked with setTimeout(0) to keep
// the UI responsive while crunching pixel data.
// ---------------------------------------------------------------------------

/** Yield a single tick so the browser can paint / handle events. */
function yieldTick(): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, 0));
}

/**
 * Load an image from a File, returning an HTMLImageElement.
 */
function loadImage(file: File): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.src = URL.createObjectURL(file);
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error("Failed to decode image"));
  });
}

/**
 * Main-thread K-Means++ color extraction.
 *
 * 1. Draw image onto a scratch <canvas> (resized to maxPx).
 * 2. Sample every 4th opaque pixel.
 * 3. K-Means++ initialisation.
 * 4. Lloyd iterations (yield after each iteration).
 * 5. Return sorted hex colours.
 */
async function extractColors(
  file: File,
  maxPx: number,
  k: number,
): Promise<string[]> {
  // ---- load & decode ----
  const img = await loadImage(file);

  // ---- scale dimensions ----
  let w = img.width;
  let h = img.height;
  if (w > maxPx || h > maxPx) {
    const ratio = Math.min(maxPx / w, maxPx / h);
    w = Math.round(w * ratio);
    h = Math.round(h * ratio);
  }

  // ---- draw to scratch canvas ----
  const canvas = document.createElement("canvas");
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas2D unavailable");
  ctx.drawImage(img, 0, 0, w, h);

  const imgData = ctx.getImageData(0, 0, w, h);
  const px = imgData.data;

  // ---- sample opaque pixels (stride 4 → every 16 bytes) ----
  const samples: [number, number, number][] = [];
  for (let i = 0; i < px.length; i += 16) {
    if (px[i + 3] >= 128) {
      samples.push([px[i], px[i + 1], px[i + 2]]);
    }
  }
  if (samples.length === 0) throw new Error("No opaque pixels found");

  const n = samples.length;
  const centroids: [number, number, number][] = [];

  // ---- K-Means++ init ----
  centroids.push(samples[Math.floor(Math.random() * n)]);

  for (let ci = 1; ci < k; ci++) {
    const dists = new Float64Array(n);
    let sum = 0;
    for (let i = 0; i < n; i++) {
      let minD = Infinity;
      const [pr, pg, pb] = samples[i];
      for (let c = 0; c < centroids.length; c++) {
        const [cr, cg, cb] = centroids[c];
        const d = (pr - cr) ** 2 + (pg - cg) ** 2 + (pb - cb) ** 2;
        if (d < minD) minD = d;
      }
      dists[i] = minD;
      sum += minD;
    }
    let r = Math.random() * sum;
    for (let i = 0; i < n; i++) {
      r -= dists[i];
      if (r <= 0) {
        centroids.push(samples[i]);
        break;
      }
    }
    if (centroids.length === ci) centroids.push(samples[n - 1]); // safe-guard
  }

  await yieldTick(); // yield after init phase

  // ---- Lloyd iteration (max 10 rounds) ----
  const labels = new Uint16Array(n);
  for (let iter = 0; iter < 10; iter++) {
    // -- assignment --
    for (let i = 0; i < n; i++) {
      const [pr, pg, pb] = samples[i];
      let best = 0;
      let bestD = Infinity;
      for (let c = 0; c < k; c++) {
        const [cr, cg, cb] = centroids[c];
        const d = (pr - cr) ** 2 + (pg - cg) ** 2 + (pb - cb) ** 2;
        if (d < bestD) {
          bestD = d;
          best = c;
        }
      }
      labels[i] = best;
    }

    // -- update centroids --
    const sums: [number, number, number, number][] = Array.from(
      { length: k },
      () => [0, 0, 0, 0],
    );
    for (let i = 0; i < n; i++) {
      const c = labels[i];
      sums[c][0] += samples[i][0];
      sums[c][1] += samples[i][1];
      sums[c][2] += samples[i][2];
      sums[c][3] += 1;
    }

    let changed = false;
    for (let c = 0; c < k; c++) {
      if (sums[c][3] === 0) continue;
      const nr = Math.round(sums[c][0] / sums[c][3]);
      const ng = Math.round(sums[c][1] / sums[c][3]);
      const nb = Math.round(sums[c][2] / sums[c][3]);
      if (centroids[c][0] !== nr || centroids[c][1] !== ng || centroids[c][2] !== nb) {
        centroids[c] = [nr, ng, nb];
        changed = true;
      }
    }
    if (!changed) break;

    // Yield to the browser after each full Lloyd round so the UI stays alive.
    await yieldTick();
  }

  // ---- sort by cluster size desc, emit hex ----
  const sizes = new Uint32Array(k);
  for (let i = 0; i < n; i++) sizes[labels[i]]++;
  const order = Array.from({ length: k }, (_, i) => i).sort(
    (a, b) => sizes[b] - sizes[a],
  );
  return order.map((i) => rgbToHex(centroids[i][0], centroids[i][1], centroids[i][2]));
}

// ---------------------------------------------------------------------------
// localStorage-backed LRU cache
// ---------------------------------------------------------------------------
class ColorCache {
  private map = new Map<string, string[]>();

  constructor() {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (raw) {
        const entries: [string, string[]][] = JSON.parse(raw);
        this.map = new Map(entries.slice(-CACHE_MAX));
      }
    } catch {
      /* quota / parse – ignore */
    }
  }

  get(key: string) {
    return this.map.get(key);
  }

  set(key: string, colors: string[]) {
    this.map.set(key, colors);
    if (this.map.size > CACHE_MAX) {
      const first = this.map.keys().next().value;
      if (first !== undefined) this.map.delete(first);
    }
    try {
      localStorage.setItem(
        STORAGE_KEY,
        JSON.stringify(Array.from(this.map.entries()).slice(-CACHE_MAX)),
      );
    } catch {
      /* quota exceeded – silently drop */
    }
  }
}

const colorCache = new ColorCache();

// ---------------------------------------------------------------------------
// Canvas drawing helper (used for preview & PNG export)
// ---------------------------------------------------------------------------
function paint(
  canvas: HTMLCanvasElement,
  stops: Stop[],
  kind: GradientKind,
  angle: number,
  radialShape: RadialShape,
) {
  const w = canvas.width;
  const h = canvas.height;
  const ctx = canvas.getContext("2d");
  if (!ctx) return;

  let grad: CanvasGradient;
  if (kind === "linear") {
    const rad = (angle * Math.PI) / 180;
    const x1 = w / 2 - Math.cos(rad) * w;
    const y1 = h / 2 - Math.sin(rad) * h;
    const x2 = w / 2 + Math.cos(rad) * w;
    const y2 = h / 2 + Math.sin(rad) * h;
    grad = ctx.createLinearGradient(x1, y1, x2, y2);
  } else {
    const cx = w / 2;
    const cy = h / 2;
    const r =
      radialShape === "circle"
        ? Math.min(w, h) / 2
        : Math.hypot(w, h) / 2;
    grad = ctx.createRadialGradient(cx, cy, 0, cx, cy, r);
  }

  for (const s of stops) {
    if (s.color) grad.addColorStop(s.position / 100, s.color);
  }

  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, w, h);
}

// =========================================================================
// Main Page Component
// =========================================================================
export default function Page() {
  // --- state ---
  const [phase, setPhase] = useState<Phase>("idle");
  const [errorText, setErrorText] = useState("");
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [stops, setStops] = useState<Stop[]>([]);
  const [kind, setKind] = useState<GradientKind>("linear");
  const [angle, setAngle] = useState(90);
  const [radialShape, setRadialShape] = useState<RadialShape>("ellipse");
  const [exportPx, setExportPx] = useState(600);
  const [dragOver, setDragOver] = useState(false);
  const [pickerIdx, setPickerIdx] = useState<number | null>(null);

  const fileRef = useRef<HTMLInputElement>(null);
  const previewRef = useRef<HTMLCanvasElement>(null);
  const exportRef = useRef<HTMLCanvasElement>(null);

  // --- repaint preview when stops / params change ---
  useEffect(() => {
    if (phase === "ready" && previewRef.current && stops.length > 0) {
      paint(previewRef.current, stops, kind, angle, radialShape);
    }
  }, [phase, stops, kind, angle, radialShape]);

  // --- core pipeline: File -> async extractColors -> stops ---
  const run = useCallback(async (file: File) => {
    // validate size
    if (file.size > MAX_FILE_BYTES) {
      setPhase("error");
      setErrorText("Image exceeds 20 MiB limit.");
      return;
    }
    if (!VALID_MIMES.has(file.type)) {
      setPhase("error");
      setErrorText("Unsupported format. Use JPEG, PNG, WebP, GIF, or BMP.");
      return;
    }

    setPhase("loading");
    setErrorText("");

    // cache key
    const key = `${file.name}|${file.size}|${file.lastModified}`;
    const cached = colorCache.get(key);
    if (cached && cached.length > 0) {
      // also set preview URL for the ready state
      const url = URL.createObjectURL(file);
      setPreviewUrl(url);
      const s: Stop[] = cached.map((c, i) => ({
        color: c,
        position: Math.round((100 / cached.length) * (i + 0.5)),
      }));
      setStops(s);
      setPhase("ready");
      return;
    }

    try {
      const url = URL.createObjectURL(file);
      setPreviewUrl(url);

      setPhase("processing");

      // Run K-Means++ on the main thread with yield points baked in.
      // The function yields between Lloyd rounds so the spinner stays animated.
      const colors = await extractColors(file, MAX_CANVAS_PX, CLUSTER_COUNT);

      const topColors = colors.slice(0, 8);
      const s: Stop[] = topColors.map((c, i) => ({
        color: c,
        position: Math.round((100 / topColors.length) * (i + 0.5)),
      }));
      setStops(s);
      colorCache.set(key, topColors);
      setPhase("ready");
    } catch (err: unknown) {
      const msg =
        err instanceof Error ? err.message : "Failed to process image.";
      setPhase("error");
      setErrorText(msg);
    }
  }, []);

  // --- reset ---
  const reset = useCallback(() => {
    if (previewUrl) URL.revokeObjectURL(previewUrl);
    setPhase("idle");
    setPreviewUrl(null);
    setStops([]);
    setErrorText("");
    setPickerIdx(null);
  }, [previewUrl]);

  // --- stop mutations ---
  const updateStop = useCallback(
    (i: number, patch: Partial<Stop>) =>
      setStops((prev) => {
        const n = [...prev];
        n[i] = { ...n[i], ...patch };
        return n;
      }),
    [],
  );

  const removeStop = useCallback(
    (i: number) => setStops((prev) => prev.filter((_, idx) => idx !== i)),
    [],
  );

  // --- export: copy CSS ---
  const copyCSS = useCallback(() => {
    const css = stopsToCSS(stops, kind, angle, radialShape);
    navigator.clipboard.writeText(`background: ${css};`).catch(() => {
      const ta = document.createElement("textarea");
      ta.value = `background: ${css};`;
      ta.style.position = "fixed";
      ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
    });
  }, [stops, kind, angle, radialShape]);

  // --- export: PNG via native canvas ---
  const downloadPNG = useCallback(() => {
    const canvas = exportRef.current;
    if (!canvas) return;
    const w = exportPx;
    const h = Math.round(exportPx * 0.6);
    canvas.width = w;
    canvas.height = h;
    paint(canvas, stops, kind, angle, radialShape);
    canvas.toBlob((blob) => {
      if (!blob) return;
      const a = document.createElement("a");
      a.href = URL.createObjectURL(blob);
      a.download = "gradient.png";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
    }, "image/png");
  }, [exportPx, stops, kind, angle, radialShape]);

  // --- export: CSS file ---
  const downloadCSS = useCallback(() => {
    const css = fullCSSText(stops, kind, angle, radialShape);
    const blob = new Blob([css], { type: "text/css" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "gradient.css";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  }, [stops, kind, angle, radialShape]);

  // --- drag handlers ---
  const onDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragOver(true);
  }, []);

  const onDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragOver(false);
  }, []);

  const onDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      e.stopPropagation();
      setDragOver(false);
      const f = e.dataTransfer.files[0];
      if (f) run(f);
    },
    [run],
  );

  const onFileChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const f = e.target.files?.[0];
      if (f) run(f);
    },
    [run],
  );

  // --- derived CSS string for display ---
  const cssPreview = useMemo(() => {
    if (phase !== "ready") return "";
    return `background: ${stopsToCSS(stops, kind, angle, radialShape)};`;
  }, [phase, stops, kind, angle, radialShape]);

  // ====================== RENDER ======================
  const busy = phase === "loading" || phase === "processing";

  return (
    <div className="flex flex-col min-h-screen">
      {/* ===================================================
           HERO / UPLOAD
      =================================================== */}
      <section className="relative flex flex-col items-center justify-center px-4 py-16 text-center">
        <h2 className="text-4xl md:text-5xl font-extrabold tracking-tight bg-gradient-to-r from-indigo-400 via-purple-400 to-cyan-400 bg-clip-text text-transparent mb-3">
          img2gradient
        </h2>
        <p className="text-gray-400 max-w-lg text-base md:text-lg mb-8">
          Extract dominant colors from any image and turn them into
          production-ready CSS gradients — 100% client-side.
        </p>

        {/* ---- drop zone ---- */}
        <div
          className={`w-full max-w-xl border-2 border-dashed rounded-2xl p-10 cursor-pointer transition-all duration-300 select-none
            ${dragOver ? "border-indigo-400 bg-indigo-400/10 scale-[1.01]" : "border-gray-600 hover:border-gray-400 bg-white/[0.03]"}
            ${busy ? "pointer-events-none opacity-60" : ""}
          `}
          onDragOver={onDragOver}
          onDragLeave={onDragLeave}
          onDrop={onDrop}
          onClick={() => fileRef.current?.click()}
        >
          <input
            ref={fileRef}
            type="file"
            accept="image/jpeg,image/png,image/webp,image/gif,image/bmp"
            className="hidden"
            onChange={onFileChange}
          />

          {phase === "idle" && (
            <div className="space-y-3">
              <svg
                className="w-14 h-14 mx-auto text-gray-500"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.5"
              >
                <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
                <polyline points="17 8 12 3 7 8" />
                <line x1="12" y1="3" x2="12" y2="15" />
              </svg>
              <p className="text-gray-300 font-medium">
                Click or drag & drop an image
              </p>
              <p className="text-xs text-gray-500">
                JPEG · PNG · WebP · GIF · BMP (max 20 MiB)
              </p>
            </div>
          )}

          {busy && (
            <div className="space-y-3">
              <div className="w-10 h-10 border-[3px] border-indigo-400 border-t-transparent rounded-full animate-spin mx-auto" />
              <p className="text-gray-400 text-sm">
                {phase === "loading"
                  ? "Decoding image…"
                  : "Clustering colors…"}
              </p>
            </div>
          )}

          {phase === "error" && (
            <div className="space-y-3">
              <svg
                className="w-14 h-14 mx-auto text-red-400"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.5"
              >
                <circle cx="12" cy="12" r="10" />
                <line x1="15" y1="9" x2="9" y2="15" />
                <line x1="9" y1="9" x2="15" y2="15" />
              </svg>
              <p className="text-red-400 font-medium">{errorText}</p>
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation();
                  reset();
                }}
                className="px-5 py-2 rounded-lg bg-red-500/20 border border-red-500/30 text-red-300 hover:bg-red-500/30 transition-colors text-sm"
              >
                Try again
              </button>
            </div>
          )}

          {phase === "ready" && previewUrl && (
            <div className="space-y-3">
              <img
                src={previewUrl}
                alt="Uploaded preview"
                className="max-h-52 mx-auto rounded-lg object-contain"
              />
              <p className="text-xs text-gray-500">
                Click to upload another image
              </p>
            </div>
          )}
        </div>
      </section>

      {/* ===================================================
           HOW IT WORKS (landing page content)
      =================================================== */}
      {phase !== "ready" && (
        <section className="max-w-4xl mx-auto px-4 pb-16 grid gap-8 md:grid-cols-3">
          <div className="bg-white/[0.03] border border-gray-700/60 rounded-2xl p-6 text-center">
            <div className="w-10 h-10 mx-auto mb-3 rounded-full bg-indigo-500/20 flex items-center justify-center">
              <svg
                className="w-5 h-5 text-indigo-400"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
              >
                <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
                <polyline points="17 8 12 3 7 8" />
                <line x1="12" y1="3" x2="12" y2="15" />
              </svg>
            </div>
            <h3 className="text-sm font-semibold text-gray-200 mb-2">
              1. Upload Image
            </h3>
            <p className="text-xs text-gray-500 leading-relaxed">
              Drag & drop any JPEG, PNG, WebP, GIF, or BMP image. Your file
              stays on your device — nothing is uploaded to any server.
            </p>
          </div>

          <div className="bg-white/[0.03] border border-gray-700/60 rounded-2xl p-6 text-center">
            <div className="w-10 h-10 mx-auto mb-3 rounded-full bg-purple-500/20 flex items-center justify-center">
              <svg
                className="w-5 h-5 text-purple-400"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
              >
                <circle cx="12" cy="12" r="3" />
                <path d="M19.4 15a1.65 1.65 0 00.33 1.82l.06.06a2 2 0 010 2.83 2 2 0 01-2.83 0l-.06-.06a1.65 1.65 0 00-1.82-.33 1.65 1.65 0 00-1 1.51V21a2 2 0 01-4 0v-.09A1.65 1.65 0 009 19.4a1.65 1.65 0 00-1.82.33l-.06.06a2 2 0 01-2.83-2.83l.06-.06A1.65 1.65 0 004.68 15a1.65 1.65 0 00-1.51-1H3a2 2 0 010-4h.09A1.65 1.65 0 004.6 9a1.65 1.65 0 00-.33-1.82l-.06-.06a2 2 0 012.83-2.83l.06.06A1.65 1.65 0 009 4.68a1.65 1.65 0 001-1.51V3a2 2 0 014 0v.09a1.65 1.65 0 001 1.51 1.65 1.65 0 001.82-.33l.06-.06a2 2 0 012.83 2.83l-.06.06A1.65 1.65 0 0019.4 9a1.65 1.65 0 001.51 1H21a2 2 0 010 4h-.09a1.65 1.65 0 00-1.51 1z" />
              </svg>
            </div>
            <h3 className="text-sm font-semibold text-gray-200 mb-2">
              2. Extract Colors
            </h3>
            <p className="text-xs text-gray-500 leading-relaxed">
              Our K-Means++ algorithm analyzes your image and extracts up to 6
              dominant colors — processed entirely in your browser.
            </p>
          </div>

          <div className="bg-white/[0.03] border border-gray-700/60 rounded-2xl p-6 text-center">
            <div className="w-10 h-10 mx-auto mb-3 rounded-full bg-cyan-500/20 flex items-center justify-center">
              <svg
                className="w-5 h-5 text-cyan-400"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
              >
                <polyline points="16 18 22 12 16 6" />
                <polyline points="8 6 2 12 8 18" />
              </svg>
            </div>
            <h3 className="text-sm font-semibold text-gray-200 mb-2">
              3. Export CSS
            </h3>
            <p className="text-xs text-gray-500 leading-relaxed">
              Copy the CSS snippet or export as a PNG/CSS file. Paste directly
              into your project — no dependencies, no framework lock-in.
            </p>
          </div>
        </section>
      )}

      {/* ===================================================
           EDITOR (shown after extraction)
      =================================================== */}
      {phase === "ready" && (
        <section className="flex-1 px-4 pb-12">
          <div className="max-w-6xl mx-auto grid gap-6 lg:grid-cols-[1fr_380px]">
            {/* ---- left: preview canvas ---- */}
            <div className="bg-white/[0.03] border border-gray-700/60 rounded-2xl overflow-hidden">
              <canvas
                ref={previewRef}
                className="w-full aspect-[16/10] block"
                width={800}
                height={500}
              />
            </div>

            {/* ---- right: controls ---- */}
            <div className="space-y-5">
              {/* palette */}
              <div className="bg-white/[0.03] border border-gray-700/60 rounded-2xl p-5">
                <h3 className="text-sm font-semibold text-gray-200 mb-3">
                  Color stops
                </h3>
                <div className="space-y-3">
                  {stops.map((s, i) => (
                    <div key={i} className="flex items-center gap-3">
                      {/* swatch + picker */}
                      <div className="relative">
                        <button
                          type="button"
                          className="w-9 h-9 rounded-lg border-2 border-gray-600 shadow-inner"
                          style={{ backgroundColor: s.color }}
                          onClick={() =>
                            setPickerIdx(pickerIdx === i ? null : i)
                          }
                        />
                        {pickerIdx === i && (
                          <div className="absolute top-12 left-1/2 -translate-x-1/2 z-30 bg-gray-800 border border-gray-600 rounded-xl p-2 shadow-2xl">
                            <input
                              type="color"
                              value={s.color}
                              onChange={(e) =>
                                updateStop(i, { color: e.target.value })
                              }
                              className="w-16 h-16 cursor-pointer block"
                            />
                          </div>
                        )}
                      </div>

                      {/* position slider */}
                      <input
                        type="range"
                        min={0}
                        max={100}
                        value={s.position}
                        onChange={(e) =>
                          updateStop(i, {
                            position: parseInt(e.target.value, 10),
                          })
                        }
                        className="flex-1 h-1 accent-indigo-500 cursor-pointer"
                      />
                      <span className="text-xs text-gray-500 w-9 text-right">
                        {s.position}%
                      </span>

                      {/* delete */}
                      {stops.length > 2 && (
                        <button
                          type="button"
                          onClick={() => removeStop(i)}
                          className="w-6 h-6 rounded-full bg-red-500/10 border border-red-500/20 text-red-400 text-xs hover:bg-red-500/20 transition-colors"
                        >
                          ×
                        </button>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              {/* gradient type & angle */}
              <div className="bg-white/[0.03] border border-gray-700/60 rounded-2xl p-5 space-y-4">
                {/* kind */}
                <div className="flex gap-2">
                  {(["linear", "radial"] as GradientKind[]).map((gk) => (
                    <button
                      key={gk}
                      type="button"
                      onClick={() => setKind(gk)}
                      className={`px-4 py-1.5 rounded-lg text-sm font-medium transition-colors ${
                        kind === gk
                          ? "bg-indigo-500/20 text-indigo-300 border border-indigo-500/30"
                          : "bg-gray-800/80 text-gray-400 border border-gray-700/50 hover:bg-gray-700"
                      }`}
                    >
                      {gk === "linear" ? "Linear" : "Radial"}
                    </button>
                  ))}
                </div>

                {kind === "linear" && (
                  <div className="flex items-center gap-3">
                    <span className="text-xs text-gray-400">Angle</span>
                    <input
                      type="range"
                      min={0}
                      max={360}
                      value={angle}
                      onChange={(e) => setAngle(parseInt(e.target.value, 10))}
                      className="flex-1 h-1 accent-indigo-500 cursor-pointer"
                    />
                    <span className="text-xs text-gray-300 w-10 text-right">
                      {angle}°
                    </span>
                  </div>
                )}

                {kind === "radial" && (
                  <div className="flex gap-2">
                    {(["circle", "ellipse"] as RadialShape[]).map((rs) => (
                      <button
                        key={rs}
                        type="button"
                        onClick={() => setRadialShape(rs)}
                        className={`px-4 py-1.5 rounded-lg text-sm font-medium capitalize transition-colors ${
                          radialShape === rs
                            ? "bg-indigo-500/20 text-indigo-300 border border-indigo-500/30"
                            : "bg-gray-800/80 text-gray-400 border border-gray-700/50 hover:bg-gray-700"
                        }`}
                      >
                        {rs}
                      </button>
                    ))}
                  </div>
                )}
              </div>

              {/* CSS output */}
              <div className="bg-white/[0.03] border border-gray-700/60 rounded-2xl p-5 space-y-3">
                <h3 className="text-sm font-semibold text-gray-200">CSS</h3>
                <pre className="bg-[#0b0f19] border border-gray-700/40 rounded-lg p-3 text-xs text-emerald-400 overflow-x-auto whitespace-pre-wrap break-all font-mono">
                  {cssPreview}
                </pre>
                <div className="flex flex-wrap gap-2">
                  <button
                    type="button"
                    onClick={copyCSS}
                    className="px-3 py-1.5 rounded-lg text-xs font-medium bg-gray-800 border border-gray-600 text-gray-300 hover:bg-gray-700 transition-colors"
                  >
                    Copy CSS
                  </button>
                  <button
                    type="button"
                    onClick={downloadCSS}
                    className="px-3 py-1.5 rounded-lg text-xs font-medium bg-gray-800 border border-gray-600 text-gray-300 hover:bg-gray-700 transition-colors"
                  >
                    Download .css
                  </button>

                  {/* PNG export controls */}
                  <span className="text-xs text-gray-500 self-center ml-2">
                    PNG
                  </span>
                  <input
                    type="number"
                    min={200}
                    max={2000}
                    step={100}
                    value={exportPx}
                    onChange={(e) =>
                      setExportPx(
                        clamp(
                          parseInt(e.target.value, 10) || 600,
                          200,
                          2000,
                        ),
                      )
                    }
                    className="w-16 px-1.5 py-1 rounded-md bg-gray-800 border border-gray-600 text-gray-200 text-xs text-center"
                  />
                  <span className="text-xs text-gray-500 self-center">px</span>
                  <button
                    type="button"
                    onClick={downloadPNG}
                    className="px-3 py-1.5 rounded-lg text-xs font-medium bg-indigo-500/20 border border-indigo-500/30 text-indigo-300 hover:bg-indigo-500/30 transition-colors"
                  >
                    Export PNG
                  </button>
                </div>
              </div>

              {/* reset */}
              <button
                type="button"
                onClick={reset}
                className="w-full py-2 rounded-lg text-sm text-gray-400 bg-gray-800/60 border border-gray-700/40 hover:bg-gray-700 transition-colors"
              >
                Upload another image
              </button>
            </div>
          </div>

          {/* ---- hidden export canvas ---- */}
          <canvas ref={exportRef} className="hidden" />
        </section>
      )}

      {/* Google AdSense — consent-aware */}
      <GoogleAd />
    </div>
  );
}
